# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 量潮网络应用标准
author: 量潮科技

# Information about where the book exists on the web
repository:
  url: https://github.com/quanttide/quanttide-specification-of-network-applications # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
